#!/bin/bash
port=22
more=true
while [ $more == true ]; do
  more=false
  if [ $1. == '' ]; then
    more=true
    shift
    port=$1
    shift
    continue
  fi
done


if [ $1. == . ]; then
  echo "USAGE: $0 username@host"
  exit
fi
if [ -f ~/.ssh/id_rsa ]; then
    echo You\'ve already generated rsa pair.
else
    echo | ssh-keygen -t rsa
fi
cat ~/.ssh/id_rsa.pub | ssh $*  'cat >> ~/.ssh/authorized_keys'

