#!/bin/bash -e

if [ -f $(dirname $0)/init.sh ]; then
  source $(dirname $0)/init.sh $(dirname $0)
elif [ -f /usr/share/bashshare/init.sh ]; then
  source /usr/share/bashshare/init.sh /usr/share/bashshare
else
  echo "Can't find bash-share script location"
  exit 1
fi


function help
{
    echo "USAGE: "
    echo "    $0 create                 to create new share"
    echo "    $0 mount  <share name>    to mount existing share"
    echo "    $0 umount <share name>    to umount existing share"
    echo "    $0 list                   to list existing shares"
    echo "    $0 delete <share name>    to remove existing share"
}

if [ "$1" == "create" ]; then
    bash $BS_ROOT/create_share.sh
    exit 0
elif [ "$1" == "mount" ]; then
    shift
    if [ "$1" == "all" ]; then
        for BS_NAME in $(share .sys-list); do
            mountpoint $BS_PREFIX/$BS_NAME 1> /dev/null 2> /dev/null || share mount $BS_NAME
        done
    else
        bash $BS_ROOT/mount_share.sh $1
    fi
elif [ "$1" == "umount" ]; then
    shift
    if [ "$1" == "all" ]; then
        for BS_NAME in $(share .sys-list); do
            mountpoint $BS_PREFIX/$BS_NAME 1> /dev/null 2> /dev/null && share umount $BS_NAME
        done
    else
        bash $BS_ROOT/mount_share.sh - $1
    fi
elif [ "$1" == "list" ]; then
    for BS_NAME in $(bash $BS_ROOT/$BS_STORAGE/list.sh); do
        source $BS_ROOT/$BS_STORAGE/read.sh
        source $BS_ROOT/$BS_TYPE/init.sh
        echo -en "\\r                                $BS_TYPE://$BS_USER@$BS_HOST:$BS_FOLDER"
        echo -en "\\r               $BS_NAME "
        echo -en "\\r[not mounted]"
        mountpoint $BS_PREFIX/$BS_NAME 1> /dev/null 2> /dev/null && echo -en "\\r[  mounted  ]"
        echo -en "\\n"
    done
elif [ "$1" == ".sys-list" ]; then
    bash $BS_ROOT/$BS_STORAGE/list.sh
elif [ "$1" == "delete" ]; then
    echo "Not implemented yet!"
else
    help
fi

