#!/bin/bash
if [ $1. == . ]; then
  echo "USAGE: $0 username@host"
  exit
fi
if [ -f .ssh/id_rsa ]; then
    echo You\'ve already generated rsa pair.
else
    echo | ssh-keygen -t rsa
fi
ssh-copy-id -i ~/.ssh/id_rsa.pub $*
